% Generated by ResumeAI Studio
\documentclass[10.5pt,letterpaper]{article}
\usepackage[top=0.5in,bottom=0.5in,left=0.65in,right=0.65in]{geometry}
\usepackage{fontawesome5}
\usepackage{titlesec}
\usepackage{hyperref}
\usepackage{enumitem}
\usepackage[dvipsnames]{xcolor}
\usepackage{tabularx}
\usepackage{microtype}
\usepackage{array}

% ─── Colors ───────────────────────────────────────────────────────────────────
\definecolor{accentred}{HTML}{e94560}
\definecolor{accentcyan}{HTML}{06b6d4}
\definecolor{darkgray}{HTML}{333333}

% ─── Section Formatting ───────────────────────────────────────────────────────
\titleformat{\section}{\large\bfseries\color{accentred}}{}{0em}{}[\vspace{1pt}\titlerule\vspace{2pt}]
\titlespacing{\section}{0pt}{10pt}{4pt}

% ─── List Formatting ──────────────────────────────────────────────────────────
\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,parsep=0pt,topsep=2pt,label=\textcolor{accentcyan}{\small$\bullet$}}

\hypersetup{colorlinks=true,urlcolor=accentcyan,linkcolor=accentcyan}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}

\begin{document}

% ─── Header ───────────────────────────────────────────────────────────────────
\begin{center}
{\Huge\bfseries\color{darkgray} ${resume.name!""}}\\[5pt]
\small\color{darkgray}
<#if resume.contact??><#assign c = resume.contact><#assign bar = r"\ \textbar\ "><#assign shown = false><#if c.phone?? && c.phone?has_content>\faPhone\ \texttt{${c.phone}}<#assign shown = true></#if><#if c.email?? && c.email?has_content><#if shown>${bar}</#if>\faEnvelope\ \href{mailto:${c.email}}{\texttt{${c.email}}}<#assign shown = true></#if><#if c.location?? && c.location?has_content><#if shown>${bar}</#if>\faMapMarker*\ ${c.location}<#assign shown = true></#if><#if c.linkedin?? && c.linkedin?has_content><#if shown>${bar}</#if>\faLinkedin\ \href{${c.linkedin}}{LinkedIn}<#assign shown = true></#if><#if c.github?? && c.github?has_content><#if shown>${bar}</#if>\faGithub\ \href{${c.github}}{GitHub}<#assign shown = true></#if><#if c.website?? && c.website?has_content><#if shown>${bar}</#if>\faGlobe\ \href{${c.website}}{Portfolio}</#if></#if>
\end{center}
\vspace{2pt}

% ─── Summary ──────────────────────────────────────────────────────────────────
<#if resume.summary?? && resume.summary?has_content>
\section{Summary}
\color{darkgray}${resume.summary}
\vspace{2pt}
</#if>

% ─── Experience ───────────────────────────────────────────────────────────────
<#if resume.experience?? && resume.experience?has_content>
\section{Experience}
<#list resume.experience as exp>
\noindent\textbf{\color{darkgray}${exp.title!""}}\hfill\textcolor{accentcyan}{\small ${exp.startDate!""}\,--\,${exp.endDate!"Present"}}\\[-2pt]
\textit{\color{darkgray}${exp.company!""}}<#if exp.location?? && exp.location?has_content>\hfill{\small\color{darkgray}\faMapMarker*\ ${exp.location}}</#if>
<#if exp.bullets?? && exp.bullets?has_content>
\begin{itemize}[topsep=3pt]
<#list exp.bullets as bullet>
  \item \color{darkgray}${bullet}
</#list>
\end{itemize}
</#if>
<#if exp?has_next>\vspace{5pt}</#if>
</#list>
</#if>

% ─── Education ────────────────────────────────────────────────────────────────
<#if resume.education?? && resume.education?has_content>
\section{Education}
<#list resume.education as edu>
\noindent\textbf{\color{darkgray}${edu.institution!""}}\hfill\textcolor{accentcyan}{\small ${edu.graduationDate!""}}\\[-2pt]
\textit{\color{darkgray}${edu.degree!""}<#if edu.field?? && edu.field?has_content>, ${edu.field}</#if>}<#if edu.gpa?? && edu.gpa?has_content>\hfill{\small\color{darkgray}GPA:\ ${edu.gpa}}</#if>
<#if edu?has_next>\vspace{4pt}</#if>
</#list>
</#if>

% ─── Skills ───────────────────────────────────────────────────────────────────
<#if resume.skillCategories?? && resume.skillCategories?has_content>
\section{Skills}
\renewcommand{\arraystretch}{1.35}
\begin{tabular}{@{}>{\bfseries\color{darkgray}\small}p{1.5in}@{\hspace{6pt}}>{\color{darkgray}\small}p{0.75\textwidth}@{}}
<#list resume.skillCategories as cat><#if cat.skills?? && cat.skills?has_content>  ${cat.category} & ${cat.skills?join(", ")} \\
</#if></#list>\end{tabular}
<#elseif resume.skills?? && resume.skills?has_content>
\section{Skills}
\renewcommand{\arraystretch}{1.35}
\begin{tabular}{@{}>{\bfseries\color{darkgray}\small}p{1.5in}@{\hspace{6pt}}>{\color{darkgray}\small}p{0.75\textwidth}@{}}
  Skills & ${resume.skills?join(", ")} \\
\end{tabular}
</#if>

% ─── Projects ─────────────────────────────────────────────────────────────────
<#if resume.projects?? && resume.projects?has_content>
\section{Projects}
<#list resume.projects as proj>
\noindent\textbf{\color{darkgray}${proj.name!""}}<#if proj.url?? && proj.url?has_content>\ \href{${proj.url}}{\textcolor{accentcyan}{\small\faLink}}</#if><#if proj.technologies?? && proj.technologies?has_content>\hfill\textcolor{accentcyan}{\small ${proj.technologies?join(r" \textbar\ ")}}</#if>
<#if proj.description?? && proj.description?has_content>\\[-2pt]\textit{\small\color{darkgray}${proj.description}}</#if>
<#if proj.bullets?? && proj.bullets?has_content>
\begin{itemize}[topsep=3pt]
<#list proj.bullets as bullet>
  \item \color{darkgray}${bullet}
</#list>
\end{itemize}
</#if>
<#if proj?has_next>\vspace{5pt}</#if>
</#list>
</#if>

% ─── Certifications ───────────────────────────────────────────────────────────
<#if resume.certifications?? && resume.certifications?has_content>
\section{Certifications}
\begin{itemize}
<#list resume.certifications as cert>
  \item \color{darkgray}${cert}
</#list>
\end{itemize}
</#if>

\end{document}
