% Generated by ResumeAI Studio – ATS-Friendly Plain Black
\documentclass[10.5pt,letterpaper]{article}
\usepackage[top=0.5in,bottom=0.5in,left=0.65in,right=0.65in]{geometry}
\usepackage{titlesec}
\usepackage{hyperref}
\usepackage{enumitem}
\usepackage{microtype}

% ─── Section Formatting ───────────────────────────────────────────────────────
\titleformat{\section}{\large\bfseries}{}{0em}{}[\vspace{1pt}\titlerule\vspace{2pt}]
\titlespacing{\section}{0pt}{10pt}{4pt}

% ─── List Formatting ──────────────────────────────────────────────────────────
\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,parsep=0pt,topsep=2pt,label=\textbullet}

\hypersetup{colorlinks=false}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}

\begin{document}

% ─── Header ───────────────────────────────────────────────────────────────────
\begin{center}
{\Huge\bfseries ${resume.name!""}}\\[4pt]
\small
<#if resume.contact??><#assign c = resume.contact><#assign bar = r"\ $|$\ "><#assign shown = false><#if c.phone?? && c.phone?has_content>${c.phone}<#assign shown = true></#if><#if c.email?? && c.email?has_content><#if shown>${bar}</#if>\href{mailto:${c.email}}{\texttt{${c.email}}}<#assign shown = true></#if><#if c.linkedin?? && c.linkedin?has_content><#if shown>${bar}</#if>\href{${c.linkedin}}{${c.linkedin}}<#assign shown = true></#if><#if c.github?? && c.github?has_content><#if shown>${bar}</#if>\href{${c.github}}{${c.github}}<#assign shown = true></#if><#if c.location?? && c.location?has_content><#if shown>${bar}</#if>${c.location}</#if></#if>
\end{center}
\vspace{2pt}

% ─── Summary ──────────────────────────────────────────────────────────────────
<#if resume.summary?? && resume.summary?has_content>
\section{Summary}
${resume.summary}
\vspace{2pt}
</#if>

% ─── Education ────────────────────────────────────────────────────────────────
<#if resume.education?? && resume.education?has_content>
\section{Education}
<#list resume.education as edu>
\noindent\textbf{${edu.institution!""}} \hfill ${edu.graduationDate!""}\\
${edu.degree!""}<#if edu.field?? && edu.field?has_content> in ${edu.field}</#if><#if edu.gpa?? && edu.gpa?has_content> \hfill GPA: ${edu.gpa}</#if>
<#if edu?has_next>\vspace{4pt}</#if>
</#list>
</#if>

% ─── Technical Skills ─────────────────────────────────────────────────────────
<#if resume.skillCategories?? && resume.skillCategories?has_content>
\section{Technical Skills}
\begin{itemize}[topsep=2pt]
<#list resume.skillCategories as cat><#if cat.skills?? && cat.skills?has_content>  \item \textbf{${cat.category}:} ${cat.skills?join(", ")}
</#if></#list>\end{itemize}
<#elseif resume.skills?? && resume.skills?has_content>
\section{Technical Skills}
\begin{itemize}[topsep=2pt]
  \item ${resume.skills?join(", ")}
\end{itemize}
</#if>

% ─── Experience ───────────────────────────────────────────────────────────────
<#if resume.experience?? && resume.experience?has_content>
\section{Experience}
<#list resume.experience as exp>
\noindent\textbf{${exp.title!""}} \hfill ${exp.startDate!""} -- ${exp.endDate!"Present"}\\
\textit{${exp.company!""}}<#if exp.location?? && exp.location?has_content>, ${exp.location}</#if>
<#if exp.bullets?? && exp.bullets?has_content>
\begin{itemize}
<#list exp.bullets as bullet>
  \item ${bullet}
</#list>
\end{itemize}
</#if>
<#if exp?has_next>\vspace{4pt}</#if>
</#list>
</#if>

% ─── Projects ─────────────────────────────────────────────────────────────────
<#if resume.projects?? && resume.projects?has_content>
\section{Projects}
<#list resume.projects as proj>
\noindent\textbf{${proj.name!""}}<#if proj.technologies?? && proj.technologies?has_content> \hfill \textit{${proj.technologies?join(", ")}}</#if>
<#if proj.description?? && proj.description?has_content>\\[-2pt]\textit{\small ${proj.description}}</#if>
<#if proj.bullets?? && proj.bullets?has_content>
\begin{itemize}
<#list proj.bullets as bullet>
  \item ${bullet}
</#list>
\end{itemize}
</#if>
<#if proj?has_next>\vspace{4pt}</#if>
</#list>
</#if>

% ─── Certifications ───────────────────────────────────────────────────────────
<#if resume.certifications?? && resume.certifications?has_content>
\section{Certifications}
\begin{itemize}
<#list resume.certifications as cert>
  \item ${cert}
</#list>
\end{itemize}
</#if>

\end{document}
